# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
  - echo "CXX14=g++ -std=c++1y -fPIC" >> ~/.R/Makevars
  
jobs:  
  r_github_packages: 
  - dkahle/mpoly
  - dkahle/latte
  - dkahle/bertini
  - coneill-math/m2r
  
  include:
  - r: devel
  - r: release