# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get -y install curl
  - sudo apt-get -y install wget
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install m4
  - sudo apt-get -y install libgmp3-dev
  # install bertini
  - curl https://bertini.nd.edu/BertiniLinux64_v1.6.tar.gz -o BertiniLinux64_v1.6.tar.gz
  - tar -xf BertiniLinux64_v1.6.tar.gz
  - export BERTINI=/home/travis/build/algstat/BertiniLinux64_v1.6
  # install latte
  - wget https://github.com/latte-int/latte/releases/download/version_1_7_5/latte-integrale-1.7.5.tar.gz
  - tar -xf latte-integrale-1.7.5.tar.gz
  - cd latte-integrale-1.7.5
  - ./configure && make
  - export LATTE=/home/travis/build/algstat/latte-integrale-1.7.5/dest/bin
  - export 4TI2=/home/travis/build/algstat/latte-integrale-1.7.5/dest/bin
  # install macaulay2
  # revert to home directory
  - cd /home/travis/build/dkahle/algstat

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"))'
  - Rscript -e 'install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)'
  - Rscript -e 'devtools::install_deps()'

script:
  - Rscript -e 'devtools::check()'

after_script:
  - tar -ztvf algstat_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
  - cat algstat.Rcheck/00*

# 
jobs:  
  r_github_packages: 
  - dkahle/mpoly
  - dkahle/latte
  - dkahle/bertini
  - coneill-math/m2r
  
  include:
  - r: devel
  - r: release